26 stanag transform refactor
albersgroup/picante pull request #47
Opened 2021-12-14 16:32 UTC by Reliquia33ad

@frizman21 @jasoncpace  Changes supporting enhancement #26.

2021-12-14 17:11 UTC, frizman21 commented
@Reliquia33ad , you sent an "@" at us, but there's no specific ask. Please advise.

2021-12-14 17:26 UTC, Reliquia33ad commented
Sorry.  No specific ask beyond review.

2021-12-16 22:32 UTC, frizman21 requested changes

2021-12-16 22:32 UTC, frizman21 commented on picante-stanag4586/src/main/java/group/albers/cst/stanag/VelocityStartGenerator.java
> +				typeClass = br.skylight.commons.dli.services.MessageType.getMessageType(typeId).getImplementation()
Why are we using the fully qualified package & classname instead of a simple import?

2021-12-16 22:32 UTC, frizman21 commented on picante-stanag4586/src/main/java/group/albers/cst/stanag/VelocityStartGenerator.java
> +				typePackage = br.skylight.commons.dli.services.MessageType.getMessageType(typeId).getImplementation()
Same question here

2021-12-16 22:32 UTC, frizman21 commented on picante-stanag4586/src/main/java/group/albers/cst/stanag/VelocityStartGenerator.java
> +				typeLength = br.skylight.commons.dli.services.MessageType.getMessageType(typeId).getMessageLength();
and here

2021-12-16 22:32 UTC, frizman21 commented on picante-stanag4586/src/main/java/group/albers/cst/stanag/transforms/auto/VehicleSteeringCommandTransform.java
> +					typt.Commanded_Heading = ((Double) parm.getValue()).floatValue();
typo? Does this compile? I realize the whole thing is commented out, but this looks like a mistake.

2021-12-16 22:32 UTC, frizman21 commented on picante-stanag4586/src/main/resources/TransformTemplate.java
> +					typt.${value.getName()} = ((Double) parm.getValue()).floatValue();
This might be source of typo. Please advise...

2021-12-16 23:01 UTC, Reliquia33ad commented on picante-stanag4586/src/main/java/group/albers/cst/stanag/VelocityStartGenerator.java
> +				typeClass = br.skylight.commons.dli.services.MessageType.getMessageType(typeId).getImplementation()
We have two classes called MessageType.  Using the fully qualified name allows us to use both and get the job done.
- group.albers.cst.primitives.MessageType;
- br.skylight.commons.dli.services.MessageType;

I'm open to alternatives.

2021-12-17 02:01 UTC, Reliquia33ad commented on picante-stanag4586/src/main/resources/TransformTemplate.java
> +					typt.${value.getName()} = ((Double) parm.getValue()).floatValue();
Good catch.  I missed this.   It is in a commented out block so it wouldn't cause a build error.  I didn't have a reason to edit this portion of the code but it appears I changed it.

2021-12-17 02:55 UTC, frizman21 commented on picante-stanag4586/src/main/java/group/albers/cst/stanag/VelocityStartGenerator.java
> +				typeClass = br.skylight.commons.dli.services.MessageType.getMessageType(typeId).getImplementation()
Yep. That'll be a good reason for it!

2021-12-17 02:59 UTC, frizman21 commented
Shouldn't we remove the TypeSupport references in the RtiHelper.java? Those shouldn't be necessary anymore, right?

2021-12-31 15:54 UTC, frizman21 commented
> ove the TypeSupport references in the RtiHelper.java? Those shouldn't be necessary anymore, right?
> 
> Also, how did you test to make sure it all still works? (not asking you to write a test, just confirming that you have some case or set of cases that you run to make sure th

Handled here:
https://github.com/albersgroup/picante/pull/48

2021-12-31 15:55 UTC, frizman21 approved these changes

2022-01-12 14:34 UTC, merged