23 rtihelper dynamic
albersgroup/picante pull request #48
Opened 2021-12-16 23:29 UTC by Reliquia33ad

RtiHelper updated to dynamically load classes.   A helper method was added to look in a list of packages for our TypeSupport classes.

2021-12-18 15:19 UTC, frizman21 commented
I saw that you closed this, but didn't merge. Please advise...

2021-12-29 17:46 UTC, Reliquia33ad commented
Reopened as a candidate for review.   Still tested by running /picante-face-rtidds/src/test/java/group/albers/cst/dds/SendAllDdsMessages.java as jUnit and looking at output.    Also did a full maven clean and package on local machine.

2021-12-31 16:17 UTC, frizman21 requested changes

2021-12-31 16:17 UTC, frizman21 commented on picante-stanag4586/src/main/java/br/skylight/commons/dli/services/MessageType.java
> +	M1101(1101, MessageSource.VSM, true, true, 1000, 	"Subsystem Status Report", SubsystemStatusReport.class, new BitmappedLOI(2,3,4,5), 5,-1),
This could be universally achieved with a second contructor for the enum. That constructor would default to -1 for this value. Unless you did this on purpose, I would implement as such. Given that we want to dynamically calculate, that constructor is long term what we're looking to do anyway.

2021-12-31 16:17 UTC, frizman21 commented on picante-stanag4586/src/main/java/group/albers/cst/stanag/VelocityStartGenerator.java
> +        File[] fileList = folder.listFiles();
aesthetic spaces issue. on this line

2021-12-31 16:17 UTC, frizman21 commented on picante-stanag4586/src/main/resources/typeMetaInfo/M00041_Loiter_Configuration.json
> -    "packageName": "br.skylight.commons.dli.vehicle",
without this package name, how are we looking up the class when the message comes in?

2022-01-03 15:57 UTC, frizman21 commented
fixes #23

2022-01-06 17:30 UTC, Reliquia33ad commented on picante-stanag4586/src/main/java/group/albers/cst/stanag/VelocityStartGenerator.java
> +        File[] fileList = folder.listFiles();
This is a tabs vs. spaces issue.   It is all lined up in Eclipse.   I'll change it.

2022-01-06 17:46 UTC, Reliquia33ad commented on picante-stanag4586/src/main/resources/typeMetaInfo/M00041_Loiter_Configuration.json
> -    "packageName": "br.skylight.commons.dli.vehicle",
The process is now driven off of the message number via br.skylight.commons.dli.services.MessageType.   I use the message number to pull the Enumeration.  The Enum has methods for puling class and length.
'''
	typeId = Integer.parseInt(type.getMessageTypeId()); 
	typeClass = br.skylight.commons.dli.services.MessageType.getMessageType(typeId).getImplementation()
						.getSimpleName();
	typePackage = br.skylight.commons.dli.services.MessageType.getMessageType(typeId).getImplementation()
						.getPackage().getName();
	typeLength = br.skylight.commons.dli.services.MessageType.getMessageType(typeId).getMessageLength();
'''
I chose this path because I thought the information in MessageType was closer to the code implementation than what was in Cameo.   Though I realize that one may generate the other.

2022-01-06 21:30 UTC, Reliquia33ad commented on picante-face-rtidds/src/main/java/group/albers/cst/dds/RtiHelper.java
> +		packageList.add("org.opengroup.FACE.DM.pmc.vm");
So I went back and have a solution using reflection to populate a Hashmap<String,Class> of all classes extending com.rti.dds.topic.TypeSupportImpl.class.  Since there are classes which are not messages (Enums and others) I have filtered out Enums and by origination package(group.albers.* and org.opengroup.FACE.DM.*). Is this more what you were looking for? @frizman21

2022-01-10 16:20 UTC, frizman21 approved these changes

2022-01-12 14:37 UTC, merged